Comments posts view
scand1ce/experts_community pull request #13
Opened 2020-09-05 22:09 UTC by scand1ce

2020-09-06 06:49 UTC, Slawikus requested changes

2020-09-06 06:49 UTC, Slawikus commented on .gitignore
>  **__init__.py
А почему это в гитигноре?

2020-09-06 06:49 UTC, Slawikus commented on .gitignore
> +docker-compose.yml
Да и докер композ же вроде для дела используется чтобы приложение локально с базой поднимать, чего его игнорить то?

2020-09-06 06:49 UTC, Slawikus commented on experts_community/settings.py
> +"""DATABASES = {
Старый кусок для коннекта к эскуэльлайту можно убрать же? Если понадобиться зачем-то в будущем то можно просто в старых коммитах подсмотреть

2020-09-06 06:49 UTC, Slawikus commented on posts/forms.py
> +        for field in self.fields:
У тебя же всего одно поле, зачем фор луп то делать?

2020-09-06 06:49 UTC, Slawikus commented on posts/models.py
>      created_at = models.DateTimeField(auto_now_add=True, verbose_name='Публикация')
А тут важно и время публикации или только даты будет достаточно?

2020-09-06 06:49 UTC, Slawikus commented on posts/models.py
> +    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE, verbose_name='Автор поста', blank=True, null=True)
Может полю on delete другое значение присвоит? Вот человек уволиться, его из системы удалят, и тогда его все посты тоже удаляться. Или удаление пользователей не предусмотрено, только их деактивация чтобы они не могли больше войти в аккаунт?

2020-09-06 06:49 UTC, Slawikus commented on posts/models.py
> +    post = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name='Пост', blank=True, null=True,
А разве коммент может жить без поста? Если нет, что вроде логично, то почему указано null True blank True?

2020-09-06 06:49 UTC, Slawikus commented on posts/models.py
> +                             related_name='comment_post')
Я бы рилэйтед нэйм дал бы просто comments. Так если есть инстанс поста то к комментам красиво было бы обращаться: post.comments а не post.comment_post (тут и множественного числа не хватает)

2020-09-06 06:49 UTC, Slawikus commented on posts/models.py
> +    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE, verbose_name='Автор комментария', blank=True,
Тоже с автором - он же всегда должен быть у комментария, разве нет?

2020-09-06 06:49 UTC, Slawikus commented on posts/views.py
> +class DetailPostsView(FormMixin, DetailView):
Вау, прикольный конструкт, я такого не видел, классно сделано!

2020-09-06 06:52 UTC, scand1ce commented on .gitignore
>  **__init__.py
Я это заигнорил в самом начале проекта, уберу.

2020-09-06 06:52 UTC, scand1ce commented on .gitignore
> +docker-compose.yml
Сделаю

2020-09-06 06:53 UTC, scand1ce commented on experts_community/settings.py
> +"""DATABASES = {
Сделаю

2020-09-06 06:58 UTC, scand1ce commented on posts/models.py
>      created_at = models.DateTimeField(auto_now_add=True, verbose_name='Публикация')
Да, время будет важным, так как иногда тяжело доказать что ты взялся за определенное дело сутра, а так описал что нужно и уже время публикации будет выступать своеобразными логами

2020-09-06 07:00 UTC, scand1ce commented on posts/models.py
> +    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE, verbose_name='Автор поста', blank=True, null=True)
Только деактивация, удалять нет смысла и посты тоже как база знаний может быть использована, нужно будет добавить поиск и возможно фильтрацию

2020-09-06 07:01 UTC, scand1ce commented on posts/models.py
> +    post = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name='Пост', blank=True, null=True,
Исправлю

2020-09-06 07:04 UTC, scand1ce commented on posts/models.py
> +                             related_name='comment_post')
Сделаю

2020-09-06 07:04 UTC, scand1ce commented on posts/models.py
> +    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE, verbose_name='Автор комментария', blank=True,
Согласен

2020-09-06 13:23 UTC, scand1ce commented on posts/forms.py
> +        for field in self.fields:
цикл удалил

2020-09-09 20:35 UTC, Slawikus approved these changes

2020-09-09 20:35 UTC, Slawikus commented on experts_community/settings.py
>      'allauth',
А как в проект просочился allauth?

2020-09-09 20:35 UTC, Slawikus commented on posts/forms.py
>              raise ValidationError('Название должно начинаться с букы!')
Опечатка в слове "буква"

2020-09-09 20:39 UTC, scand1ce commented on posts/forms.py
>              raise ValidationError('Название должно начинаться с букы!')
поменяю

2020-09-09 20:39 UTC, scand1ce commented on experts_community/settings.py
>      'allauth',
удалю

2020-09-09 20:59 UTC, merged