Factory for data base
scand1ce/experts_community pull request #14
Opened 2020-09-13 22:09 UTC by scand1ce

2020-09-14 19:09 UTC, Slawikus requested changes

2020-09-14 19:09 UTC, Slawikus commented on commands/management/commands/factories.py
> +        CommentFactory.create_batch(10)
Я бы наверное по креативные чуток это сделал бы. Создал бы несколько юзеров сначала, штуки 3, дал бы им ФИО толковые, потом для каждого создал бы посты и комменты (разного количества). Все это через фабрики само собой.
А так как оно есть немного скучновато - десять юзеров, у каждого по одному посту и у поста только один коммент.

2020-09-14 19:19 UTC, scand1ce commented on posts/tests/comment_factories.py
> +    comment_text = factory.Faker('paragraph')
нет, даже об этом не подумал

2020-09-14 19:20 UTC, scand1ce commented on posts/tests/posts_factories.py
> +    title = factory.Sequence(lambda n: 'TEST_title%s' % n)
понял

2020-09-14 19:20 UTC, scand1ce commented on posts/tests/posts_factories.py
> +    created_at = factory.LazyAttribute(lambda x: now())
понял

2020-09-14 19:21 UTC, scand1ce commented on users/tests/users_factories.py
> +    username = factory.Sequence(lambda n: 'TEST_username%s' % n)
сделаю

2020-09-14 19:21 UTC, scand1ce commented on users/tests/users_factories.py
> +    email = 'email@email.email'
сделаю

2020-09-14 19:21 UTC, scand1ce commented on users/tests/users_factories.py
> +    is_superuser = True
сделаю

2020-09-14 19:32 UTC, scand1ce commented on commands/management/commands/factories.py
> +        CommentFactory.create_batch(10)
с ФИО фейкер норм создает (например Susan Decker), а по поводу разного количества, сделаю как надо.

2020-09-14 19:33 UTC, scand1ce commented on my-admin/tests/factories.py
> +print("admin")
удалю

2020-09-14 19:34 UTC, scand1ce commented on posts/tests/comment_factories.py
> +    created_at = factory.LazyAttribute(lambda x: now())
сделаю

2020-09-15 18:55 UTC, scand1ce commented on posts/tests/comment_factories.py
> +    created_at = factory.LazyAttribute(lambda x: now())
сделано

2020-09-15 19:24 UTC, scand1ce commented on posts/tests/posts_factories.py
> +
удалил

2020-09-15 19:25 UTC, scand1ce commented on users/tests/users_factories.py
> +    username = factory.Sequence(lambda n: 'TEST_username%s' % n)
сделал

2020-09-15 21:13 UTC, scand1ce commented on posts/tests/posts_factories.py
> +    content = factory.Sequence(lambda n: 'TEST_content%s' % n)
done

2020-09-18 17:45 UTC, merged