Chat
scand1ce/experts_community pull request #19
Opened 2020-10-07 13:53 UTC by scand1ce

AsyncWebSocket

2020-10-11 13:21 UTC, Slawikus commented on chat/consumers.py
> +        self.room_name = self.scope['url_route']['kwargs']['room_name']
А зачем ты из риквеста выковыриваешь название комнаты? Я думал у тебя будет одна конкретная комната для чата, разве нет?

2020-10-11 13:21 UTC, Slawikus commented on chat/routing.py
> +    re_path(r'ws/chat/(?P<room_name>\w+)/$', consumers.ChatConsumer),
Тут тоже самое - разве тебе надо иметь комнаты с любым названием?

2020-10-11 13:21 UTC, Slawikus commented on chat/consumers.py
> +        await self.accept()
Тут надо ж как-то авторизовать пользователя чтобы только те кто залогинены могли бы иметь доступ к чату

2020-10-11 20:53 UTC, scand1ce commented on chat/consumers.py
> +'''import json
Сделано

2020-10-11 22:32 UTC, scand1ce commented on chat/consumers.py
> +        self.room_name = self.scope['url_route']['kwargs']['room_name']
Решил, но очень не замысловато, в следующих ПР доработаю

2020-10-11 22:32 UTC, scand1ce commented on chat/routing.py
> +    re_path(r'ws/chat/(?P<room_name>\w+)/$', consumers.ChatConsumer),
Решил, но очень не замысловато, в следующих ПР доработаю

2020-10-12 11:17 UTC, scand1ce commented on chat/consumers.py
> +        await self.accept()
ограничил на странице html

2020-10-12 11:47 UTC, Slawikus commented on chat/consumers.py
> +        await self.accept()
С точки зрения безопасности это не решение. Ты просто прячешь страницу и все, но пользователь знающий урл комнаты сможет напрямую к ней подключиться.

2020-10-12 11:54 UTC, Slawikus requested changes

2020-10-12 11:54 UTC, Slawikus commented on chat/consumers.py
> +            self.channel_name
А где и как определяется channel name?

2020-10-12 11:54 UTC, Slawikus commented on templates/chat/chat.html
> +{% if user.is_authenticated %}
У тебя только залогиненые пользователи должны видеть страницу чата, поэтому это проверку здесь делать смысла нет - лучше сразу обесопасить вьюху с декоратором login_required
Но это не отменяет проблемы безопасности вебсокет конекшена упомянутый ранее

2020-10-12 12:24 UTC, scand1ce commented on chat/consumers.py
> +        await self.accept()
я не смог подключится, разлогинился и вбил урл, кидает условие которое я указал

2020-10-12 12:25 UTC, scand1ce commented on chat/consumers.py
> +            self.channel_name
я просто сделал вот так
```
    async def connect(self):
        user = self.scope["session"]["_auth_user"] 
        self.room_name = 'general'
        self.room_group_name = 'general'
```

2020-10-12 12:27 UTC, scand1ce commented on templates/chat/chat.html
> +{% if user.is_authenticated %}
я понял, буду пробовать дальше, выше упомянутый тоже буду менять

2020-10-12 12:31 UTC, Slawikus commented on chat/consumers.py
> +        await self.accept()
А ты пробовал разлогиниться и через вебсокет клиент к урлю вебсоткета подключиться, к тому что начинается на ws://

2020-10-12 12:33 UTC, Slawikus commented on chat/consumers.py
> +            self.channel_name
Я ж спрашивал про channel name в строке 21. Откуда он берётся? Его библиотека сама генерирует или как это работает?

2020-10-12 12:50 UTC, scand1ce commented on chat/consumers.py
> +        await self.accept()
не подумал об этом, делаю как надо

2020-10-14 12:06 UTC, Slawikus commented on chat/views.py
> +def chat(request, room_name='general'):  # Will be add private room fo UserToUser
Ты ж его так и не закрыл для не залогиненых пользователей

2020-10-14 12:06 UTC, Slawikus commented on commands/management/commands/t.py
> +'''Команда для проверки последнего входа в систему
А эта команда зачем ?

2020-10-14 12:06 UTC, Slawikus commented on templates/chat/chat.html
> +{% if user.is_authenticated %}
Это так и не поменял

2020-10-14 12:12 UTC, scand1ce commented on commands/management/commands/t.py
> +'''Команда для проверки последнего входа в систему
чтоб смотреть заходили под этим юзернеймом или нет, я этого юзера создал специально и закидываю вместе с сылкой на проджкт и резюмехой

2020-10-14 12:43 UTC, scand1ce commented on templates/chat/chat.html
> +{% if user.is_authenticated %}
готово

2020-10-14 13:09 UTC, merged